version: "3.9"

services:
  backend:
    build: ./backend
    container_name: stockapp-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: stockapp-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   
    depends_on:
      - backend